#!/bin/bash -e

echo "Making Citron for MacOS"
if [ "$TARGET" = "arm64" ]; then
    export LIBVULKAN_PATH="/opt/homebrew/lib/libvulkan.1.dylib"
else
    export LIBVULKAN_PATH="/usr/local/lib/libvulkan.1.dylib"
fi

cd ./citron

# hook the updater to check my repo
# git apply ../patches/update.patch

COUNT="$(git rev-list --count HEAD)"
APP_NAME="Citron-${COUNT}-MacOS-${TARGET}"

mkdir -p build
cd build
cmake .. -GNinja \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCITRON_USE_BUNDLED_VCPKG=OFF \
    -DCITRON_USE_BUNDLED_QT=OFF \
    -DUSE_SYSTEM_QT=ON \
    -DENABLE_QT6=ON \
    -DCITRON_USE_BUNDLED_FFMPEG=OFF \
    -DCITRON_USE_BUNDLED_SDL2=ON \
    -DCITRON_USE_EXTERNAL_SDL2=OFF \
    -DCITRON_TESTS=OFF \
    -DCITRON_CHECK_SUBMODULES=OFF \
    -DCITRON_USE_LLVM_DEMANGLE=OFF \
    -DCITRON_ENABLE_LTO=ON \
    -DCITRON_USE_QT_MULTIMEDIA=ON \
    -DCITRON_USE_QT_WEB_ENGINE=OFF \
    -DENABLE_QT_TRANSLATION=ON \
    -DUSE_DISCORD_PRESENCE=ON \
    -DENABLE_WEB_SERVICE=ON \
    -DENABLE_OPENSSL=ON \
    -DBUNDLE_SPEEX=ON \
    -DCITRON_USE_FASTER_LD=OFF \
    -DCITRON_USE_EXTERNAL_Vulkan_HEADERS=ON \
    -DCITRON_USE_EXTERNAL_VULKAN_UTILITY_LIBRARIES=ON \
    -DCITRON_USE_AUTO_UPDATER=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_CXX_FLAGS="$ARCH_FLAGS -Wno-error -w ${CXX_FLAGS_EXTRA}" \
    -DCMAKE_C_FLAGS="$ARCH_FLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR="$(uname -m)" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DBUILD_TESTING=OFF \
    -DDYNARMIC_TESTS=OFF \
    -DCITRON_USE_EXTERNAL_SDL2=ON \
    -DCITRON_USE_EXTERNAL_FFMPEG=ON \
    -DCITRON_USE_BUNDLED_SIRIT=ON \
    -DCITRON_USE_CPM=ON \
    -DENABLE_UPDATE_CHECKER=ON \
    -DUSE_DISCORD_PRESENCE=OFF \
    -DCITRON_CMD=OFF \
    -DCITRON_ROOM_STANDALONE=OFF \
    -DCMAKE_OSX_ARCHITECTURES="$TARGET" \
    -DCMAKE_CXX_FLAGS="-w" \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCITRON_USE_PRECOMPILED_HEADERS=OFF 
    # -DCITRON_TESTS=OFF \
	# -DBUILD_TESTING=OFF \
 	# -DDYNARMIC_TESTS=OFF \
    # -DCITRON_USE_BUNDLED_QT=OFF \
	# -DCITRON_USE_EXTERNAL_SDL2=ON \
	# -DCITRON_USE_EXTERNAL_FFMPEG=ON \
	# -DCITRON_USE_BUNDLED_SIRIT=ON \
	# -DCITRON_USE_CPM=ON \
	# -DCITRON_USE_FASTER_LD=OFF \
    # -DENABLE_QT_TRANSLATION=ON \
	# -DENABLE_UPDATE_CHECKER=ON \
    # -DCITRON_ENABLE_LTO=ON \
    # -DUSE_DISCORD_PRESENCE=OFF \
    # -DCITRON_CMD=OFF \
    # -DCITRON_ROOM_STANDALONE=OFF \
    # -DCMAKE_OSX_ARCHITECTURES="$TARGET" \
    # -DCMAKE_CXX_FLAGS="-w" \
    # -DCMAKE_BUILD_TYPE=Release \
    # -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    # -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    # -DCITRON_USE_PRECOMPILED_HEADERS=OFF 
    
ninja
ccache -s -v

# Bundle and code-sign citron.app.
APP=./bin/citron.app
macdeployqt "$APP"
codesign --deep --force --verify --verbose --sign - "$APP"

# Pack for upload
mkdir -p artifacts
mkdir "$APP_NAME"
cp -a ./bin/. "$APP_NAME"
ZIP_NAME="$APP_NAME.7z"
7z a -t7z -mx=9 "$ZIP_NAME" "$APP_NAME"
mv "$ZIP_NAME" artifacts/

echo "Build completed successfully."
